/*******************************************************************************
 * JMMC project ( http://www.jmmc.fr ) - Copyright (C) CNRS.
 ******************************************************************************/
package fr.jmmc.oiexplorer.gui;

import fr.jmmc.jmcs.gui.component.GenericListModel;
import fr.jmmc.oiexplorer.core.model.OIFitsCollection;
import fr.jmmc.oiexplorer.core.model.OIFitsManager;
import fr.jmmc.oiexplorer.core.model.event.OIFitsCollectionEvent;
import fr.jmmc.oiexplorer.core.model.event.OIFitsCollectionListener;
import fr.jmmc.oitools.model.OIFitsFile;

/**
 * Main container of OIFits Explorer App
 * @author mella
 */
public class MainPanel extends javax.swing.JPanel implements OIFitsCollectionListener {

    /** Creates new form MainPanel */
    public MainPanel() {
        initComponents();
        postInitComponents();
    }

    private void postInitComponents() {
        OIFitsManager.getInstance().register(this);
    }


  /**
   * Refresh the list of OIfits files
   */
  private void updateOIFitsList(final OIFitsCollection oiFitsCollection) {

    final Object oldValue = this.jListOIFitsFiles.getSelectedValue();

    this.jListOIFitsFiles.setModel(new GenericListModel<OIFitsFile>(oiFitsCollection.getOIFitsFiles()));

      // restore previous selected item :
    this.jListOIFitsFiles.setSelectedValue(oldValue, true);
  }    
    
  /**
   * Handle the given OIFits collection event
   * @param event OIFits collection event
   */    
    @Override
    public void onProcess(final OIFitsCollectionEvent event) {
        switch (event.getType()) {
            case CHANGED:
                updateOIFitsList(event.getOIFitsCollection());
                break;
            default:
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane = new javax.swing.JSplitPane();
        jScrollPaneList = new javax.swing.JScrollPane();
        jListOIFitsFiles = new javax.swing.JList();

        setLayout(new java.awt.GridBagLayout());

        jListOIFitsFiles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneList.setViewportView(jListOIFitsFiles);

        jSplitPane.setLeftComponent(jScrollPaneList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jSplitPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jListOIFitsFiles;
    private javax.swing.JScrollPane jScrollPaneList;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
