/*******************************************************************************
 * JMMC project ( http://www.jmmc.fr ) - Copyright (C) CNRS.
 ******************************************************************************/
package fr.jmmc.oiexplorer.gui;

import fr.jmmc.oiexplorer.core.gui.Vis2Panel;
import fr.jmmc.oiexplorer.core.model.OIFitsCollectionManager;
import fr.jmmc.oiexplorer.core.model.OIFitsCollectionManagerEvent;
import fr.jmmc.oiexplorer.core.model.OIFitsCollectionManagerEventListener;
import fr.jmmc.oiexplorer.core.model.OIFitsCollectionManagerEventType;
import fr.jmmc.oiexplorer.core.model.oi.Plot;
import fr.jmmc.oiexplorer.core.model.oi.SubsetDefinition;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author mella
 */
public final class PlotView extends javax.swing.JPanel implements OIFitsCollectionManagerEventListener {

    /** default serial UID for Serializable interface */
    private static final long serialVersionUID = 1;
    /** Class logger */
    private static final Logger logger = LoggerFactory.getLogger(PlotView.class.getName());

    /* members */
    /** OIFitsCollectionManager singleton reference */
    private final OIFitsCollectionManager ocm = OIFitsCollectionManager.getInstance();
    /** related plot identifier */
    private final String plotId;

    /** 
     * Creates new form PlotView 
     * @param plotId plot identifier
     */
    public PlotView(final String plotId) {
        ocm.getSubsetDefinitionChangedEventNotifier().register(this);

        // Build GUI
        initComponents();

        this.plotId = plotId;

        // Finish init
        postInit();
    }

    /**
     * This method is useful to set the models and specific features of initialized swing components :
     */
    private void postInit() {
        plotEditor.initialize(plotId);
        vis2Panel.setPlotId(plotId);

        // hide PlotDefinitionEditor by default
        editToggleButton.setSelected(false);
        editToggleButtonActionPerformed(null);
    }

    /**
     * Refresh the HTML view
     * @param subsetDefinition subset definition
     */
    private void updateHtmlView(final SubsetDefinition subsetDefinition) {
        this.oIFitsHtmlPanel.updateOIFits(subsetDefinition.getOIFitsSubset());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneViews = new javax.swing.JTabbedPane();
        plotPanel = new javax.swing.JPanel();
        northPanel = new javax.swing.JPanel();
        plotEditor = new fr.jmmc.oiexplorer.core.gui.PlotEditor();
        editToggleButton = new javax.swing.JToggleButton();
        vis2Panel = new fr.jmmc.oiexplorer.core.gui.Vis2Panel();
        plotDefinitionEditor = new fr.jmmc.oiexplorer.core.gui.PlotDefinitionEditor();
        oIFitsHtmlPanel = new fr.jmmc.oiexplorer.core.gui.OIFitsHtmlPanel();

        setLayout(new java.awt.BorderLayout());

        plotPanel.setLayout(new java.awt.BorderLayout());

        northPanel.add(plotEditor);

        editToggleButton.setText("edit");
        editToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editToggleButtonActionPerformed(evt);
            }
        });
        northPanel.add(editToggleButton);

        plotPanel.add(northPanel, java.awt.BorderLayout.NORTH);
        plotPanel.add(vis2Panel, java.awt.BorderLayout.CENTER);
        plotPanel.add(plotDefinitionEditor, java.awt.BorderLayout.SOUTH);

        jTabbedPaneViews.addTab("plot", plotPanel);
        jTabbedPaneViews.addTab("data", oIFitsHtmlPanel);

        add(jTabbedPaneViews, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void editToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editToggleButtonActionPerformed
        final boolean displayPlotDefEditor = editToggleButton.isSelected();
        plotDefinitionEditor.setVisible(displayPlotDefEditor);
        if (displayPlotDefEditor) {
            plotDefinitionEditor.setPlotId(plotId);
        } else {
            plotDefinitionEditor.setPlotId(null);
        }

    }//GEN-LAST:event_editToggleButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton editToggleButton;
    private javax.swing.JTabbedPane jTabbedPaneViews;
    private javax.swing.JPanel northPanel;
    private fr.jmmc.oiexplorer.core.gui.OIFitsHtmlPanel oIFitsHtmlPanel;
    private fr.jmmc.oiexplorer.core.gui.PlotDefinitionEditor plotDefinitionEditor;
    private fr.jmmc.oiexplorer.core.gui.PlotEditor plotEditor;
    private javax.swing.JPanel plotPanel;
    private fr.jmmc.oiexplorer.core.gui.Vis2Panel vis2Panel;
    // End of variables declaration//GEN-END:variables

    public Vis2Panel getPlotPanel() {
        return vis2Panel;
    }

    public String getPlotId() {
        return plotId;
    }

    /*
     * OIFitsCollectionManagerEventListener implementation 
     */
    /**
     * Return the optional subject id i.e. related object id that this listener accepts
     * @param type event type
     * @return subject id (null means accept any event) or DISCARDED_SUBJECT_ID to discard event
     */
    public String getSubjectId(final OIFitsCollectionManagerEventType type) {
        // TODO: find better solution (plot ?)
        switch (type) {
            case SUBSET_CHANGED:
                // Get SubsetId corresponding to the latest plot instance:
                final Plot plot = ocm.getPlotRef(plotId);
                if (plot != null && plot.getSubsetDefinition() != null) {
                    return plot.getSubsetDefinition().getName();
                }
                break;
            default:
        }
        return DISCARDED_SUBJECT_ID;
    }

    /**
     * Handle the given OIFits collection event
     * @param event OIFits collection event
     */
    @Override
    public void onProcess(final OIFitsCollectionManagerEvent event) {
        logger.debug("onProcess {}", event);

        switch (event.getType()) {
            case SUBSET_CHANGED:
                updateHtmlView(event.getSubsetDefinition());
                break;
            default:
        }
        logger.debug("onProcess {} - done", event);
    }
}
