/*******************************************************************************
 * JMMC project ( http://www.jmmc.fr ) - Copyright (C) CNRS.
 ******************************************************************************/
package fr.jmmc.oiexplorer.gui;

import fr.jmmc.oiexplorer.core.gui.Vis2Panel;
import fr.jmmc.oiexplorer.core.model.OIFitsCollectionEventListener;
import fr.jmmc.oiexplorer.core.model.OIFitsCollectionManager;
import fr.jmmc.oiexplorer.core.model.event.GenericEvent;
import fr.jmmc.oiexplorer.core.model.event.OIFitsCollectionEventType;
import fr.jmmc.oiexplorer.core.model.event.SubsetDefinitionEvent;
import fr.jmmc.oiexplorer.core.model.oi.Plot;
import fr.jmmc.oiexplorer.core.model.oi.SubsetDefinition;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author mella
 */
public final class PlotView extends javax.swing.JPanel implements OIFitsCollectionEventListener {

    /** default serial UID for Serializable interface */
    private static final long serialVersionUID = 1;
    /** Class logger */
    protected static final Logger logger = LoggerFactory.getLogger(PlotView.class.getName());

    /* members */
    /** OIFitsCollectionManager singleton reference */
    private final OIFitsCollectionManager ocm = OIFitsCollectionManager.getInstance();
    /** related plot identifier */
    private final String plotId;

    /** 
     * Creates new form PlotView 
     * @param plotId plot identifier
     */
    public PlotView(final String plotId) {
        ocm.getSubsetDefinitionEventNotifier().register(this);

        // Build GUI
        initComponents();

        this.plotId = plotId;

        // Finish init
        postInit();
    }

    /**
     * This method is useful to set the models and specific features of initialized swing components :
     */
    private void postInit() {
        vis2Panel.setPlotId(plotId);
        plotEditor.setPlotId(plotId);
    }

    /**
     * Refresh the HTML view
     * @param subsetDefinition subset definition
     */
    private void updateHtmlView(final SubsetDefinition subsetDefinition) {
        this.oIFitsHtmlPanel.updateOIFits(subsetDefinition.getOIFitsSubset());
    }

    /* --- OIFitsCollectionEventListener implementation --- */
    /**
     * Return the optional subject id i.e. related object id that this listener accepts
     * @see GenericEvent#subjectId
     * @param type event type
     * @return subject id i.e. related object id (null allowed)
     */
    public String getSubjectId(final OIFitsCollectionEventType type) {
        // Get SubsetId corresponding to the latest plot instance:
        final Plot plot = ocm.getPlotRef(this.plotId);
        if (plot != null) {
            return (plot.getSubsetDefinition() != null) ? plot.getSubsetDefinition().getName() : null;
        }
        return null;
    }

    /**
     * Handle the given OIFits collection event
     * @param event OIFits collection event
     */
    @Override
    public void onProcess(GenericEvent<OIFitsCollectionEventType> event) {
        logger.warn("onProcess : {}", event);

        switch (event.getType()) {
            case SUBSET_CHANGED:
                updateHtmlView(((SubsetDefinitionEvent) event).getSubsetDefinition());
                break;
            default:
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneViews = new javax.swing.JTabbedPane();
        plotPanel = new javax.swing.JPanel();
        plotEditor = new fr.jmmc.oiexplorer.core.gui.PlotEditor();
        vis2Panel = new fr.jmmc.oiexplorer.core.gui.Vis2Panel();
        oIFitsHtmlPanel = new fr.jmmc.oiexplorer.core.gui.OIFitsHtmlPanel();

        setLayout(new java.awt.BorderLayout());

        plotPanel.setLayout(new java.awt.BorderLayout());
        plotPanel.add(plotEditor, java.awt.BorderLayout.NORTH);
        plotPanel.add(vis2Panel, java.awt.BorderLayout.CENTER);

        jTabbedPaneViews.addTab("plot", plotPanel);
        jTabbedPaneViews.addTab("data", oIFitsHtmlPanel);

        add(jTabbedPaneViews, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPaneViews;
    private fr.jmmc.oiexplorer.core.gui.OIFitsHtmlPanel oIFitsHtmlPanel;
    private fr.jmmc.oiexplorer.core.gui.PlotEditor plotEditor;
    private javax.swing.JPanel plotPanel;
    private fr.jmmc.oiexplorer.core.gui.Vis2Panel vis2Panel;
    // End of variables declaration//GEN-END:variables

    public Vis2Panel getPlotPanel() {
        return vis2Panel;
    }

    public String getPlotId() {
        return plotId;
    }
}
