language: java
sudo: false

jdk:
  - openjdk8

before_install:
  - export MAVEN_OPTS="-Xms128M -Xmx1024M"
  - cd parent-pom
  - mvn -Dassembly.skipAssembly -Djarsigner.skip=true clean install
  - cd ..
  - mvn process-resources

before_script:
  - echo $HOME
  - echo $MAVEN_OPTS

script: 
  - mvn clean install -Djarsigner.skip=true -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -Djava.util.logging.config.file=./src/test/resources/logging.properties -Djarsigner.skip=true -B

install: true

cache:
  directories:
    - $HOME/.m2

