language: java

jdk:
  - openjdk8

before_install:
  - export MAVEN_OPTS="-Xms128M -Xmx1024M"
  - cd parent-pom
  - mvn -Dassembly.skipAssembly -Djarsigner.skip=true clean install
  - cd ..
  - mvn process-resources

before_script:
  - echo $HOME
  - echo $MAVEN_OPTS

script:
  - mvn clean install -Djarsigner.skip=true -DskipTests=true  -B -V
  - mvn test -Djava.util.logging.config.file=./src/test/resources/logging.properties -Djarsigner.skip=true -B

install: true

after_success:
- touch target/apidocs/.nojekyll
- mv  rules/{DataModelV1_output.html,DataModelV2_output.html} target/apidocs/.
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: target/apidocs
  committer_from_gh: true
  on:
    branch: master

cache:
  directories:
    - $HOME/.m2
